// Generated by LiveScript 1.5.0
/**
 * @package blake2.wasm
 * @author  Nazar Mokrynskyi <nazar@mokrynskyi.com>
 * @license 0BSD
 */
(function(){
  var lib, test, vectors;
  lib = require('..');
  test = require('tape');
  vectors = require('../vendor/testvectors/blake2-kat.json');
  function hex2bin(hex){
    return Buffer.from(hex, 'hex');
  }
  function bin2hex(bin){
    return Buffer.from(bin).toString('hex');
  }
  lib.ready(function(){
    test('Running test vectors', function(t){
      var i$, ref$, len$, vector, input, key, output;
      for (i$ = 0, len$ = (ref$ = vectors).length; i$ < len$; ++i$) {
        vector = ref$[i$];
        switch (vector.hash) {
        case 'blake2b':
          input = hex2bin(vector['in']);
          key = hex2bin(vector.key);
          output = lib.Blake2b(64, key).update(input).final();
          t.equal(bin2hex(output), vector.out);
          break;
        case 'blake2s':
          input = hex2bin(vector['in']);
          key = hex2bin(vector.key);
          output = lib.Blake2s(32, key).update(input).final();
          t.equal(bin2hex(output), vector.out);
          break;
        default:

        }
      }
      t.end();
    });
  });
}).call(this);
